# Generated by Django 5.0.6 on 2024-12-20 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0002_recipe_user_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 20, 10, 17, 48, 337743, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
